## Copyright (c) 2022, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

title: "Create highly available Tomcat setup with web application accessing MDS in Oracle Cloud Infrastructure"
stackDescription: "Deploy highly available Tomcat setup with web application accessing MySQL Database Service (MDS) in Oracle Cloud Infrastructure."
schemaVersion: 1.1.0
version: "20190404"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
  - tenancy_ocid
  - region
  - release
  - availability_domain_number
  - use_existing_vcn
  - use_existing_nsg
  - vcn_id
  - lb_subnet_id
  - fss_subnet_id
  - lb_nsg_ids
  - compute_subnet_id
  - compute_nsg_ids
  - mysql_db_system_subnet_id
  - bastion_subnet_id
  - bastion_nsg_ids
  - mysql_db_system_maintenance_window_start_time

- title: Required Configuration
  visible: true  
  variables:
  - compartment_ocid
  - availability_domain_name
  - mysql_db_system_admin_password
  - mysql_db_system_password
  - numberOfNodes
  - tomcat_version
  - use_bastion_service
  - show_advanced

- title: Load Balancer Configuration
  visible: 
      and:
        - show_advanced
  variables:
  - lb_shape 
  - flex_lb_min_shape
  - flex_lb_max_shape 

- title: Network Configuration
  visible: 
      and:
        - show_advanced
  variables:
  - tomcat_mds_vcn_cidr_block
  - tomcat_mds_vcn_dns_label
  - tomcat_mds_vcn_display_name
  - tomcat_mds_vcn_subnet_lb_cidr_block
  - tomcat_mds_vcn_subnet_lb_display_name
  - tomcat_mds_vcn_subnet_bastion_cidr_block
  - tomcat_mds_vcn_subnet_bastion_display_name  
  - tomcat_mds_vcn_subnet_app_cidr_block
  - tomcat_mds_vcn_subnet_app_display_name 
  - tomcat_mds_vcn_subnet_fss_cidr_block
  - tomcat_mds_vcn_subnet_fss_display_name 
  - tomcat_mds_vcn_subnet_db_cidr_block
  - tomcat_mds_vcn_subnet_db_display_name

- title: Tomcat Compute Instances Configuration
  visible: 
      and:
        - show_advanced
  variables:
  - ssh_public_key
  - InstanceShape
  - InstanceFlexShapeOCPUS
  - InstanceFlexShapeMemory
  - instance_os
  - linux_os_version

- title: Bastion Compute Instances Configuration
  visible: 
      and:
        - show_advanced
  variables:
  - BastionShape
  - BastionFlexShapeOCPUS
  - BastionFlexShapeMemory

- title: MySQL Database System Configuration
  visible: 
      and:
        - show_advanced
  variables: 
  - mysql_db_system_shape
  - mysql_db_system_is_highly_available
  - mysql_db_system_db_name 
  - mysql_db_system_admin_username
  - mysql_db_system_username
  - mysql_db_name
  - mysql_db_system_description
  - mysql_db_system_backup_policy_is_enabled
  - mysql_db_system_data_storage_size_in_gb
  - mysql_db_system_fault_domain
  - mysql_db_system_display_name
  - mysql_db_system_hostname_label

variables:

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false
  
  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    visibile: true
    title: Compartment
    description: "Compartment where you want to create the solution resources"

  region:
    type: oci:identity:region:name
    required: true
    visibile: true
    title: Region
    description: "Region where you want to deploy the resources defined by this stack."

  availability_domain_name:
    type: oci:identity:availabilitydomain:name
    required: true
    visibile: true
    title: "Availability Domain to be chosen"
    description: "Availability Domain to be chosen"
    dependsOn:
      compartmentId: ${compartment_ocid}

  numberOfNodes:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 2
    title: "How many Tomcat Nodes?"
    description: "Choose number of Tomcat Nodes to be deployed."

  use_bastion_service:
    type: boolean
    visibile: true
    default: false
    required: false
    title: "Use OCI Bastion Service"
    description: "Check the box to use OCI Bastion Service instead of Bastion Host VM."

  tomcat_version:
    type: enum
    title: "Tomcat Version"
    description: "Choose Tomcat Version"
    default: "9.0.45"
    required: false 
    enum:
      - "9.0.45"
      - "8.5.65"
      - "7.0.108"

  mysql_db_system_admin_password:
    type: password
    required: true
    visibile: true
    title: "MySQL Database System Admin Password"
    description: "Type MySQL Database System (MDS) Admin Password"
    minLength: 9
    maxLength: 30
    pattern: ^[A-Za-z][A-Za-z0-9_#\$]+$ 

  mysql_db_system_password:
    type: password
    required: true
    visibile: true
    title: "MySQL Database System User Password"
    description: "Type MySQL Database System (MDS) User Password"
    minLength: 9
    maxLength: 30
    pattern: ^[A-Za-z][A-Za-z0-9_#\$]+$ 
 
  # Optional Configuration  
  
  lb_shape:
    type: enum
    title: "LoadBalancer Shape"
    description: "Choose LoadBalancer Shape"
    default: "flexible"
    required: false 
    enum:
      - "flexible"
      - "100Mbps"
      - "10Mbps"
      - "10Mbps-Micro"
      - "400Mbps"
      - "8000Mbps"

  flex_lb_min_shape:
    type: enum
    required: false
    default: "10"
    title: "LB Flex Min Shape"
    description: "Choose Minimum Shape for Flex Load Balancer."
    enum:
      - "10"
      - "100"
      - "1000"
      - "400"
      - "8000"
    visible:
      and:
        - eq:
          - lb_shape 
          - "flexible"

  flex_lb_max_shape:
    type: enum
    required: false
    default: "100"
    title: "LB Flex Max Shape"
    description: "Choose Maximum Shape for Flex Load Balancer."
    enum:
      - "10"
      - "100"
      - "1000"
      - "400"
      - "8000"
    visible:
      and:
        - eq:
          - lb_shape 
          - "flexible"

  tomcat_mds_vcn_cidr_block:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "VCN CIDR Block"
    description: "Choose CIDR block for your VCN."

  tomcat_mds_vcn_display_name:
    type: string
    required: false
    title: "VCN Display Name"
    description: "Choose Display Name for your VCN."
    default: "tomcat_mds_vcn"

  tomcat_mds_vcn_subnet_lb_cidr_block:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Load Balancer Public Subnet CIDR Block"
    description: "Choose CIDR block for your Load Balancer Public Subnet."

  tomcat_mds_vcn_subnet_lb_display_name:
    type: string
    required: false
    title: "Load Balancer Public Subnet Display Name"
    description: "Choose Display Name for your Load Balancer Public Subnet."
    default: "tomcat_mds_vcn_subnet_lb"

  tomcat_mds_vcn_subnet_bastion_cidr_block:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Bastion Host Public Subnet CIDR Block"
    description: "Choose CIDR block for your Bastion Host Public Subnet."

  tomcat_mds_vcn_subnet_bastion_display_name:
    type: string
    required: false
    title: "Bastion Host Public Subnet Display Name"
    description: "Choose Display Name for your Bastion Host Public Subnet."
    default: "tomcat_mds_vcn_subnet_bastion"

  tomcat_mds_vcn_subnet_app_cidr_block:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Tomcat Servers Public Subnet CIDR Block"
    description: "Choose CIDR block for your Tomcat Servers Public Subnet."

  tomcat_mds_vcn_subnet_app_display_name:
    type: string
    required: false
    title: "Tomcat Servers Public Subnet Display Name"
    description: "Choose Display Name for your Tomcat Servers Public Subnet."
    default: "tomcat_mds_vcn_subnet_app"

  tomcat_mds_vcn_subnet_fss_cidr_block:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "FSS Subnet CIDR Block"
    description: "Choose CIDR block for your FSS Subnet."

  tomcat_mds_vcn_subnet_fss_display_name:
    type: string
    required: false
    title: "FSS Subnet Display Name"
    description: "Choose Display Name for your FSS Subnet."
    default: "tomcat_mds_vcn_subnet_fss"

  tomcat_mds_vcn_subnet_db_cidr_block:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "MDS Private Subnet CIDR Block"
    description: "Choose CIDR block for your MDS Private Subnet."

  tomcat_mds_vcn_subnet_db_display_name:
    type: string
    required: false
    title: "MDS Private Subnet Display Name"
    description: "Choose Display Name for your MDS Private Subnet."
    default: "tomcat_mds_vcn_subnet_db"

  ssh_public_key:
    type: oci:core:ssh:publickey
    title: "Public SSH Key"
    description: "Choose public SSH Key to be uploaded into compute instances."
    required: false
    
  InstanceShape:
    type: oci:core:instanceshape:name
    required: false
    title: "Instance Shape"
    description: "A shape is a template that determines the number of CPUs, amount of memory, and other resources allocated to a newly created instance."
    default: "VM.Standard.E3.Flex"
    dependsOn:
      compartmentId: ${compartment_ocid}

  InstanceFlexShapeOCPUS:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - or:
          - eq:
            - InstanceShape 
            - "VM.Standard.E3.Flex"
          - eq:
            - InstanceShape 
            - "VM.Standard.E4.Flex"
          - eq:
            - InstanceShape 
            - "VM.Standard.A1.Flex"
          - eq:
            - InstanceShape 
            - "VM.Optimized3.Flex"

  InstanceFlexShapeMemory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 6
    title: "Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
      and:
        - or:
          - eq:
            - InstanceShape 
            - "VM.Standard.E3.Flex"
          - eq:
            - InstanceShape 
            - "VM.Standard.E4.Flex"
          - eq:
            - InstanceShape 
            - "VM.Standard.A1.Flex"
          - eq:
            - InstanceShape 
            - "VM.Optimized3.Flex"

  BastionShape:
    type: oci:core:instanceshape:name
    required: false
    title: "Bastion VM Shape"
    description: "A shape is a template that determines the number of CPUs, amount of memory, and other resources allocated to a newly created instance."
    default: "VM.Standard.E3.Flex"
    dependsOn:
      compartmentId: ${compartment_ocid}
    visible:
      and:
        - eq:
          - use_bastion_service
          - false

  BastionFlexShapeOCPUS:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Bastion Shape Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - eq:
          - use_bastion_service
          - false
        - or:
          - eq:
            - BastionShape 
            - "VM.Standard.E3.Flex"
          - eq:
            - BastionShape 
            - "VM.Standard.E4.Flex"
          - eq:
            - BastionShape 
            - "VM.Standard.A1.Flex"
          - eq:
            - BastionShape 
            - "VM.Optimized3.Flex"


  BastionFlexShapeMemory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Bastion Shape Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
      and:
        - eq:
          - use_bastion_service
          - false
        - or:
          - eq:
            - BastionShape 
            - "VM.Standard.E3.Flex"
          - eq:
            - BastionShape 
            - "VM.Standard.E4.Flex"
          - eq:
            - BastionShape 
            - "VM.Standard.A1.Flex"
          - eq:
            - BastionShape 
            - "VM.Optimized3.Flex"

  instance_os:
    type: enum
    required: false
    title: "Instance OS"
    description: "An Operating System that determines the operating system for the instance."
    default: "Oracle Linux"
    enum:
      - "Oracle Linux"

  linux_os_version:
    type: enum
    required: false
    title: "Instance OS version"
    description: "An Operating System version that determines the operating system version for the instance."
    default: "8"
    enum:
      - "8"

  mysql_db_system_shape:
    type: enum
    required: false
    default: "MySQL.VM.Standard.E3.1.8GB"
    title: "MySQL Database System Shape"
    description: "Choose MySQL Database System Shape (MDS) for your deployment."
    enum:
      - "VM.Standard.E2.1"
      - "VM.Standard.E2.2"
      - "VM.Standard.E2.4"  
      - "VM.Standard.E2.8"
      - "MySQL.VM.Standard.E3.1.8GB"
      - "MySQL.VM.Standard.E3.1.16GB"      
      - "MySQL.VM.Standard.E3.2.32GB"
      - "MySQL.VM.Standard.E3.4.64GB"
      - "MySQL.VM.Standard.E3.8.128GB"
      - "MySQL.VM.Standard.E3.16.256GB"
      - "MySQL.VM.Standard.E3.24.384GB"
      - "MySQL.VM.Standard.E3.32.512GB"
      - "MySQL.VM.Standard.E3.48.768GB"    
      - "MySQL.VM.Standard.E3.64.1024GB"  
      - "MySQL.HeatWave.VM.Standard.E3"      
  
  mysql_db_system_fault_domain:
    type: enum
    required: false
    default: "FAULT-DOMAIN-1"
    title: "MySQL Database System Fault Domain"
    description: "Choose MySQL Database System (MDS) Fault Domain for your deployment."
    enum:
      - "FAULT-DOMAIN-1"
      - "FAULT-DOMAIN-2"
      - "FAULT-DOMAIN-3" 

  mysql_db_system_is_highly_available:
    type: boolean
    visibile: true
    default: false
    title: "MySQL Database System highly available?"
    description: "Check the box to setup MySQL Database System highly available."      

  mysql_db_system_admin_username:
    type: string
    required: false
    title: "MySQL Database System Admin Username"
    description: "Type Database System (MDS) Admin Username."
    default: "admin"

  mysql_db_system_description:
    type: string
    required: false
    title: "MySQL Database System Description"
    description: "MySQL Database System (MDS) Description."
    default: "Tomcat MySQL Database System"

  mysql_db_system_db_name:
    type: string
    required: false
    title: "MySQL Database System DB Name"
    description: "Type MySQL Database System (MDS) DB Name."
    default: "TomcatMDS"

  mysql_db_system_backup_policy_is_enabled:
    type: boolean 
    default: true
    required: false
    title: "MySQL Database System Backup Policy Enabled"
    description: "MySQL Database System (MDS) Backup Policy Enabled."

  mysql_db_system_data_storage_size_in_gb:
    type: number
    required: false
    minimum: 50
    maximum: 65536
    multipleOf: 1
    default: 50 
    title: "MySQL Database System Data Storage size in GB"
    description: "Choose MySQL Database System (MDS) Data Storage size in GB."

  mysql_db_system_username:
    type: string
    required: false
    title: "MySQL Database System User Name"
    description: "Type MySQL Database System (MDS) User Name."

  mysql_db_system_display_name: 
    type: string
    required: false
    title: "MySQL Database System Display Name"
    description: "Type MySQL Database System (MDS) Display Name."

  mysql_db_system_hostname_label: 
    type: string
    required: false
    title: "MySQL Database System Hostname Label"
    description: "Type MySQL Database System (MDS) Hostname Label."

  release:
    type: string
    required: false
    visible: false
    title: "Reference Architecture Release (OCI Architecture Center)"

outputs:

  tomcat_home_URL:
    title: "Tomcat Home URL"
    displayText: "Tomcat Home URL"
    type: copyableString
    visible: true

  tomcat_demo_app_URL:
    title: "Tomcat Demo APP (todoapp) URL"
    displayText: "Tomcat Demo APP (todoapp) URL"
    type: copyableString
    visible: true
